data:
  name: 'Darcy'
  datapath: "/data/yangchangfan/DiffusionPDE/data/testing/darcy.mat"
  offset: 1001

test:
  pre-trained: "/data/yangchangfan/DiffusionPDE/pretrained-models/pretrained-darcy.pkl"
  iterations: 2000

generate:
  seed: 0
  device: 'cuda'
  batch_size: 1
  sigma_min: 0.002
  sigma_max: 80
  rho: 7
  zeta_obs_a: 2500
  zeta_obs_u: 1000000
  zeta_pde: 1000